apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sasa
  name: minecraft-yomogi
  labels:
    app: minecraft-yomogi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-yomogi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-yomogi
    spec:
      containers:
        - image: itzg/minecraft-server:java17
          name: minecraft-yomogi
          env:
            - name: TYPE
              value: PAPER
            - name: ENABLE_RCON
              value: "true"
            - name: VERSION
              value: "1.18.2"
            - name: UID
              value: "0"
            - name: GID
              value: "0"
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
            - name: minecraft-yomogi-storage
              mountPath: /data
      volumes:
        - name: minecraft-yomogi-storage
          persistentVolumeClaim:
            claimName: minecraft-yomogi-pvc
