apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sasa
  name: minecraft-yomogi-pvc
  labels:
    app: minecraft-yomogi
spec:
  storageClassName: minecraft-yomogi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi