apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: minecraft-main-pv
  labels:
    app: minecraft-main
spec:
  storageClassName: minecraft-main
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.1.200
    path: /exports/fast-drive-02/k8s/sasa/minecraft/main
  persistentVolumeReclaimPolicy: Delete
