apiVersion: v1
kind: Service
metadata:
  namespace: sasa
  name: minecraft-main
  labels:
    app: minecraft-main
spec:
  ports:
    - name: server
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: dynmap
      protocol: TCP
      port: 8123
      targetPort: 8123
  selector:
    app: minecraft-main
