apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-sub-pvc
  namespace: sasa
spec:
  storageClassName: mysql-sub-pv-class
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
