apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sasa
  name: minecraft-resource-pvc
  labels:
    app: minecraft-resource
spec:
  storageClassName: minecraft-resource
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi