apiVersion: v1
kind: Service
metadata:
  namespace: sasa
  name: db-mysql-main
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: db-mysql-main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sasa
  name: db-mysql-main
spec:
  selector:
    matchLabels:
      app: db-mysql-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-mysql-main
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: common_password
            - name: TZ
              value: "Asia/Tokyo"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: db-mysql-conf
              mountPath: /etc/mysql/conf.d
            - name: db-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-mysql-conf
          configMap:
            name: db-mysql-config
        - name: db-mysql-data
          persistentVolumeClaim:
            claimName: db-mysql-main-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-main-pvc
  namespace: sasa
spec:
  storageClassName: mysql-main-pv-class
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: db-mysql-main-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-main-pv-class
  nfs:
    server: 192.168.1.200
    path: /exports/fast-drive-01/k8s/sasa/database/mysql-main
