apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dn5
  name: discord-bot-pv
  labels:
    app: discord-bot
spec:
  storageClassName: discord-bot
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.1.200
    path: /exports/slow-drive-01/k8s/dn5/discord-bot
  persistentVolumeReclaimPolicy: Delete
