apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: minecraft-lobby-pv
  labels:
    app: minecraft-lobby
spec:
  storageClassName: minecraft-lobby
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.1.200
    path: /exports/fast-drive-02/k8s/sasa/minecraft/lobby
  persistentVolumeReclaimPolicy: Delete
