apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sasa
  name: minecraft-lobby-pvc
  labels:
    app: minecraft-lobby
spec:
  storageClassName: minecraft-lobby
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi