apiVersion: v1
kind: Service
metadata:
  namespace: sasa
  name: minecraft-lobby
  labels:
    app: minecraft-lobby
spec:
  ports:
    - name: server
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: bluemap
      protocol: TCP
      port: 8100
      targetPort: 8100
  selector:
    app: minecraft-lobby
