apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: db-mongo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mongo-pv-class
  nfs:
    server: 192.168.1.200
    path: /exports/slow-drive-01/k8s/sasa/database/mongo
