apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sasa
  name: db-mongo-pvc
spec:
  storageClassName: mongo-pv-class
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
