apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: sasa
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          env:
            - name: PMA_ABSOLUTE_URI
              value: https://_k8s.dn5.run/sasa/phpmyadmin/
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOSTS
              value: db-mysql-main,db-mysql-sub
            - name: PMA_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
