apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-warp
  namespace: system
spec:
  selector:
    matchLabels:
      app: cloudflare-warp
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflare-warp
    spec:
      containers:
        - name: cloudflare-warp
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflare-access-credentials
        - name: config
          configMap:
            name: cloudflare-warp
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-warp
  namespace: system
data:
  config.yaml: |
    tunnel: _vpn
    credentials-file: /etc/cloudflared/creds/warp.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    warp-routing:
      enabled: true
