apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: minecraft-proxy-pv
  labels:
    app: minecraft-proxy
spec:
  storageClassName: minecraft-proxy
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.1.200
    path: /exports/fast-drive-02/k8s/sasa/minecraft/proxy.modern
  persistentVolumeReclaimPolicy: Delete
