apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sasa
  name: minecraft-proxy-pvc
  labels:
    app: minecraft-proxy
spec:
  storageClassName: minecraft-proxy
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi