apiVersion: v1
kind: Service
metadata:
  namespace: sasa
  name: minecraft-proxy
  labels:
    app: minecraft-proxy
spec:
  ports:
    - name: java
      protocol: TCP
      port: 41130
      targetPort: 41130
    - name: be
      protocol: UDP
      port: 41130
      targetPort: 41130
  selector:
    app: minecraft-proxy
  type: LoadBalancer
  loadBalancerIP: 192.168.1.210
