apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sasa
  name: db-mysql-main
spec:
  selector:
    matchLabels:
      app: db-mysql-main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db-mysql-main
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
            - name: TZ
              value: "Asia/Tokyo"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: db-mysql-conf
              mountPath: /etc/mysql/conf.d
            - name: db-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-mysql-conf
          configMap:
            name: db-mysql-config
        - name: db-mysql-data
          persistentVolumeClaim:
            claimName: db-mysql-main-pvc
