apiVersion: v1
kind: Service
metadata:
  namespace: sasa
  name: db-mysql-main
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: db-mysql-main
