apiVersion: v1
kind: Service
metadata:
  namespace: sasa
  name: minecraft-test
  labels:
    app: minecraft-test
spec:
  ports:
    - name: java
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app: minecraft-test
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sasa
  name: pv-mc
  labels:
    app: minecraft-test
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  nfs:
    server: 192.168.1.200
    path: /exports/fast-drive-01/k8s/minecraft-test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sasa
  name: pv-mc-claim
  labels:
    app: minecraft-test
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sasa
  name: minecraft-test-deployment
  labels:
    app: minecraft-test
spec:
  selector:
    matchLabels:
      app: minecraft-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-test
    spec:
      containers:
        - image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          name: minecraft-test
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Asia/Tokyo
            - name: TYPE
              value: PAPER
            - name: VERSION
              value: 1.18.2
            # - name: OVERRIDE_SERVER_PROPERTIES
            #   value: "TRUE"
            - name: DIFFICULTY
              value: normal
            - name: SPAWN_PROTECTION
              value: "4"
            - name: OPS
              value: "ddpn08"
            #- name: OVERRIDE_WHITELIST
            #  value: "true"
            #- name: SIMULATION_DISTANCE
            #  value: "4"
            #- name: VIEW_DISTANCE
            #  value: "15"
            # - name: ONLINE_MODE
            #   value: "FALSE"
            # - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            #   value: "true"
            # - name: REMOVE_OLD_MODS
            #   value: "TRUE"
            # - name: REMOVE_OLD_MODS_INCLUDE
            #   value: "*.jar"
            # - name: REMOVE_OLD_MODS_DEPTH
            #   value: "1"
          resources:
            limits:
              memory: 2Gi
              cpu: 1500m
            requests:
              memory: 2Gi
              cpu: 1500m
          ports:
            - name: java
              containerPort: 25565
          volumeMounts:
            - name: minecraft-test-storage
              mountPath: /data
      volumes:
        - name: minecraft-test-storage
          persistentVolumeClaim:
            claimName: pv-mc-claim
